---
 - name: jenkins-playbook
   hosts: build_server
   vars:
     dockerfile_path: ""
     destination_path: ""
   tasks:
    - name: copy Dockerfile
      copy:
        src: "{{ dockerfile_path }}"
        dest: "{{ destination_path }}"
